name: feature-branch

on: pull_request

jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Run tests
      run: make test

    - name: Upload Codecov report
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
